1 getforces: (DD15) Module constants is not defined
2 getforces: (DD15) Module communication is not defined
3 getforces: (DD15) Module blockpointers is not defined
4 getforces: (DD15) Module inputphysics is not defined
5 getforces: (DD15) Module utils is not defined
6 getforces: (DD15) Module surfaceintegrations is not defined
7 getforces: (DD15) Module surfacefamilies is not defined
8 getforces: (DD15) Module oversetdata is not defined
9 getforces: (DD15) Module surfacefamilies is not defined
10 getforces: (DD15) Module petsc is not defined
11 getforces: (TC21) No implicit rule available to complete the declaration of variable nlocalvalues
12 getforces: (TC21) No implicit rule available to complete the declaration of variable ncostfunction
13 getforces: (TC62) Undeclared type: zippermesh
14 getforces: (TC62) Undeclared type: familyexchange
15 getforces: (TC20) Variable ndom is not declared
16 getforces: (TC33) External procedure setpointers is not declared
17 getforces: (TC20) Variable zero is not declared
18 getforces: (TC20) Variable fullfamlist is not declared
19 getforces: (TC33) External procedure integratesurfaces is not declared
20 getforces: (TC20) Variable forcesastractions is not declared
21 getforces: (TC33) External procedure computenodaltractions is not declared
22 getforces: (TC33) External procedure computenodalforces is not declared
23 getforces: (TC20) Variable nbocos is not declared
24 getforces: (TC33) External procedure bctype is not declared
25 getforces: (TC20) Variable eulerwall is not declared
26 getforces: (TC20) Variable nswalladiabatic is not declared
27 getforces: (TC20) Variable nswallisothermal is not declared
28 getforces: (TC33) External procedure bcdata is not declared
29 getforces: (TC20) Variable ibcgroupwalls is not declared
30 getforces: (TC33) External procedure zippermeshes is not declared
31 getforces: (TC33) External procedure bcfamexchange is not declared
32 getforces: (TC20) Variable oversetpresent is not declared
33 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
34 getforces: (TC33) External procedure terminate is not declared
35 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
36 getforces: (TC33) External procedure vecgetarrayf90 is not declared
37 getforces: (TC20) Variable __file__ is not declared
38 getforces: (TC20) Variable __line__ is not declared
39 getforces: (TC33) External procedure echk is not declared
40 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
41 getforces: (TC33) External procedure vecrestorearrayf90 is not declared
42 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
43 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
44 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
45 getforces: (TC20) Variable insert_values is not declared
46 getforces: (TC20) Variable scatter_forward is not declared
47 getforces: (TC33) External procedure vecscatterbegin is not declared
48 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
49 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
50 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
51 getforces: (TC33) External procedure vecscatterend is not declared
52 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
53 getforces: (TC20) Variable myid is not declared
54 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
55 getforces: (TC49) Unknown return type for function bctype 
56 getforces: (TC44) Could not find type of result of function bctype, please check
57 getforces: (TC44) Could not find type of result of function bctype, please check
58 getforces: (TC44) Could not find type of result of function bctype, please check
59 getforces: Tool: (TypeSpec tree regeneration) null actualTypeSpec
60 getforces: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#15==0null*=>HB#13) label:100
61 getforces: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#16==0null*=>HB#13) label:100
62 getheatflux: (DD15) Module constants is not defined
63 getheatflux: (DD15) Module blockpointers is not defined
64 getheatflux: (DD15) Module surfacefamilies is not defined
65 getheatflux: (DD15) Module utils is not defined
66 getheatflux: (TC62) Undeclared type: familyexchange
67 getheatflux: (TC20) Variable ibcgroupwalls is not declared
68 getheatflux: (TC20) Variable ndom is not declared
69 getheatflux: (TC20) Variable nbocos is not declared
70 getheatflux: (TC20) Variable nswallisothermal is not declared
71 getheatflux: (TC60) bcdata(mm).cellval must be a pointer
72 getheatflux: (TC20) Variable eulerwall is not declared
73 getheatflux: (TC20) Variable nswalladiabatic is not declared
74 getheatflux: (TC20) Variable zerocellval is not declared
75 getheatflux: (TC60) bcdata(mm).cellval must be a pointer
76 getheatflux: (TC20) Variable zeronodeval is not declared
77 getheatflux: (TC60) bcdata(mm).nodeval must be a pointer
78 getheatflux: (TC33) External procedure computeweighting is not declared
79 getheatflux: (TC60) bcdata(mm).cellval must be a pointer
80 getheatflux: (TC60) bcdata(mm).nodeval must be a pointer
81 getheatflux: (TC33) External procedure surfacecellcentertonode is not declared
82 getheatflux: (TC20) Variable zero is not declared
83 getheatflux: (TC49) Unknown return type for function bctype 
84 getheatflux: (TC44) Could not find type of result of function bctype, please check
85 getheatflux: (TC44) Could not find type of result of function bctype, please check
86 getheatflux: (TC44) Could not find type of result of function bctype, please check
87 getheatflux: (TC44) Could not find type of result of function bctype, please check
88 getheatflux: (TC44) Could not find type of result of function bctype, please check
89 getheatflux: (TC44) Could not find type of result of function bctype, please check
90 getheatflux: (TC44) Could not find type of result of function bctype, please check
91 getheatflux: (DF03) variable ndom is used before initialized
92 getheatflux: (DF03) variable nbocos is used before initialized
93 getheatflux: (DF03) variable nswallisothermal is used before initialized
94 getheatflux: (DF03) variable eulerwall is used before initialized
95 getheatflux: (DF03) variable nswalladiabatic is used before initialized
96 getheatflux: (DF03) variable ndom is used before initialized
97 getheatflux: (DF03) variable nbocos is used before initialized
98 getheatflux: (DF03) variable nswallisothermal is used before initialized
99 getheatflux: (DF03) variable ndom is used before initialized
100 getheatflux: (DF03) variable nbocos is used before initialized
101 getheatflux: (DF03) variable nswallisothermal is used before initialized
102 getheatflux: (DF03) variable nswalladiabatic is used before initialized
103 getheatflux: (DF03) variable eulerwall is used before initialized
104 getheatflux: (DF03) variable zero is used before initialized
105 getheatflux: Tool: (Differentiate reference) Unexpected operator: call
106 getheatflux: Tool: (TypeSpec tree regeneration) null actualTypeSpec
107 getheatflux: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#22==0null*=>HB#21) label:100
108 getheatflux: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#27==0null*=>HB#26) label:110
109 heatfluxes: (DD15) Module constants is not defined
110 heatfluxes: (DD15) Module blockpointers is not defined
111 heatfluxes: (DD15) Module bcpointers is not defined
112 heatfluxes: (DD15) Module flowvarrefstate is not defined
113 heatfluxes: (DD15) Module utils is not defined
114 heatfluxes: (TC20) Variable pref is not declared
115 heatfluxes: (TC20) Variable rhoref is not declared
116 heatfluxes: (TC20) Variable nbocos is not declared
117 heatfluxes: (TC20) Variable nswallisothermal is not declared
118 heatfluxes: (TC33) External procedure setbcpointers is not declared
119 heatfluxes: (TC33) External procedure bcfaceid is not declared
120 heatfluxes: (TC20) Variable imin is not declared
121 heatfluxes: (TC20) Variable jmin is not declared
122 heatfluxes: (TC20) Variable kmin is not declared
123 heatfluxes: (TC20) Variable imax is not declared
124 heatfluxes: (TC20) Variable jmax is not declared
125 heatfluxes: (TC20) Variable kmax is not declared
126 heatfluxes: (TC20) Variable one is not declared
127 heatfluxes: (TC33) External procedure ssi is not declared
128 heatfluxes: (TC33) External procedure viscsubface is not declared
129 heatfluxes: (TC49) Unknown return type for function bctype 
130 heatfluxes: (TC49) Unknown return type for function bcfaceid 
131 heatfluxes: (TC44) Could not find type of result of function bctype, please check
132 heatfluxes: (TC44) Could not find type of result of function bcfaceid, please check
133 heatfluxes: (DF03) variable pref is used before initialized
134 heatfluxes: (DF03) variable rhoref is used before initialized
135 heatfluxes: (DF03) variable pref is used before initialized
136 heatfluxes: (DF03) variable nbocos is used before initialized
137 heatfluxes: (DF03) variable nswallisothermal is used before initialized
138 heatfluxes: (DF03) variable one is used before initialized
139 heatfluxes: (DF03) variable one is used before initialized
140 heatfluxes: Tool: (TypeSpec tree regeneration) null actualTypeSpec
141 heatfluxes: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#9==0null*=>HB#8) label:100
142 getforces_cd: (DD15) Module constants is not defined
143 getforces_cd: (DD15) Module communication is not defined
144 getforces_cd: (DD15) Module blockpointers is not defined
145 getforces_cd: (DD15) Module inputphysics is not defined
146 getforces_cd: (DD15) Module utils is not defined
147 getforces_cd: (DD15) Module surfaceintegrations is not defined
148 getforces_cd: (DD15) Module surfacefamilies is not defined
149 getforces_cd: (DD15) Module oversetdata is not defined
150 getforces_cd: (DD15) Module surfacefamilies is not defined
151 getforces_cd: (DD15) Module petsc is not defined
152 getforces_cd: (TC21) No implicit rule available to complete the declaration of variable nlocalvalues
153 getforces_cd: (TC21) No implicit rule available to complete the declaration of variable ncostfunction
154 getforces_cd: (TC62) Undeclared type: zippermesh
155 getforces_cd: (TC62) Undeclared type: familyexchange
156 getforces_cd: (TC20) Variable ndom is not declared
157 getforces_cd: (TC33) External procedure setpointers is not declared
158 getforces_cd: (TC20) Variable zero is not declared
159 getforces_cd: (TC20) Variable fullfamlist is not declared
160 getforces_cd: (TC33) External procedure integratesurfaces is not declared
161 getforces_cd: (TC20) Variable forcesastractions is not declared
162 getforces_cd: (TC33) External procedure computenodaltractions is not declared
163 getforces_cd: (TC33) External procedure computenodalforces is not declared
164 getforces_cd: (TC20) Variable nbocos is not declared
165 getforces_cd: (TC33) External procedure bctype is not declared
166 getforces_cd: (TC20) Variable eulerwall is not declared
167 getforces_cd: (TC20) Variable nswalladiabatic is not declared
168 getforces_cd: (TC20) Variable nswallisothermal is not declared
169 getforces_cd: (TC33) External procedure bcdata is not declared
170 getforces_cd: (TC20) Variable ibcgroupwalls is not declared
171 getforces_cd: (TC33) External procedure zippermeshes is not declared
172 getforces_cd: (TC33) External procedure bcfamexchange is not declared
173 getforces_cd: (TC20) Variable oversetpresent is not declared
174 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
175 getforces_cd: (TC33) External procedure terminate is not declared
176 getforces_cd: (TC03) Expression is expected to be a record, and is here familyexchange
177 getforces_cd: (TC33) External procedure vecgetarrayf90 is not declared
178 getforces_cd: (TC20) Variable __file__ is not declared
179 getforces_cd: (TC20) Variable __line__ is not declared
180 getforces_cd: (TC33) External procedure echk is not declared
181 getforces_cd: (TC03) Expression is expected to be a record, and is here familyexchange
182 getforces_cd: (TC33) External procedure vecrestorearrayf90 is not declared
183 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
184 getforces_cd: (TC03) Expression is expected to be a record, and is here familyexchange
185 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
186 getforces_cd: (TC20) Variable insert_values is not declared
187 getforces_cd: (TC20) Variable scatter_forward is not declared
188 getforces_cd: (TC33) External procedure vecscatterbegin is not declared
189 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
190 getforces_cd: (TC03) Expression is expected to be a record, and is here familyexchange
191 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
192 getforces_cd: (TC33) External procedure vecscatterend is not declared
193 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
194 getforces_cd: (TC20) Variable myid is not declared
195 getforces_cd: (TC03) Expression is expected to be a record, and is here zippermesh
196 getforces_cd: (TC49) Unknown return type for function bctype 
197 getforces_cd: (TC44) Could not find type of result of function bctype, please check
198 getforces_cd: (TC44) Could not find type of result of function bctype, please check
199 getforces_cd: (TC44) Could not find type of result of function bctype, please check
200 getforces_cd: Tool: (TypeSpec tree regeneration) null actualTypeSpec
201 getforces_cd: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#15==0null*=>HB#13) label:100
202 getforces_cd: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#16==0null*=>HB#13) label:100
203 getheatflux_d: Tool: (TypeSpec tree regeneration) null actualTypeSpec
204 getheatflux_d: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#22==0null==>HB#21) label:100
205 getheatflux_d: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#27==0null==>HB#26) label:110
206 getheatflux_cd: (DD15) Module constants is not defined
207 getheatflux_cd: (DD15) Module blockpointers is not defined
208 getheatflux_cd: (DD15) Module surfacefamilies is not defined
209 getheatflux_cd: (DD15) Module utils is not defined
210 getheatflux_cd: (TC62) Undeclared type: familyexchange
211 getheatflux_cd: (TC20) Variable ibcgroupwalls is not declared
212 getheatflux_cd: (TC20) Variable ndom is not declared
213 getheatflux_cd: (TC20) Variable nbocos is not declared
214 getheatflux_cd: (TC20) Variable nswallisothermal is not declared
215 getheatflux_cd: (TC60) bcdata(mm).cellval must be a pointer
216 getheatflux_cd: (TC20) Variable eulerwall is not declared
217 getheatflux_cd: (TC20) Variable nswalladiabatic is not declared
218 getheatflux_cd: (TC20) Variable zerocellval is not declared
219 getheatflux_cd: (TC60) bcdata(mm).cellval must be a pointer
220 getheatflux_cd: (TC20) Variable zeronodeval is not declared
221 getheatflux_cd: (TC60) bcdata(mm).nodeval must be a pointer
222 getheatflux_cd: (TC33) External procedure computeweighting is not declared
223 getheatflux_cd: (TC60) bcdata(mm).cellval must be a pointer
224 getheatflux_cd: (TC60) bcdata(mm).nodeval must be a pointer
225 getheatflux_cd: (TC33) External procedure surfacecellcentertonode is not declared
226 getheatflux_cd: (TC20) Variable zero is not declared
227 getheatflux_cd: (TC49) Unknown return type for function bctype 
228 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
229 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
230 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
231 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
232 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
233 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
234 getheatflux_cd: (TC44) Could not find type of result of function bctype, please check
235 getheatflux_cd: (DF03) variable ndom is used before initialized
236 getheatflux_cd: (DF03) variable nbocos is used before initialized
237 getheatflux_cd: (DF03) variable nswallisothermal is used before initialized
238 getheatflux_cd: (DF03) variable eulerwall is used before initialized
239 getheatflux_cd: (DF03) variable nswalladiabatic is used before initialized
240 getheatflux_cd: (DF03) variable ndom is used before initialized
241 getheatflux_cd: (DF03) variable nbocos is used before initialized
242 getheatflux_cd: (DF03) variable nswallisothermal is used before initialized
243 getheatflux_cd: (DF03) variable ndom is used before initialized
244 getheatflux_cd: (DF03) variable nbocos is used before initialized
245 getheatflux_cd: (DF03) variable nswallisothermal is used before initialized
246 getheatflux_cd: (DF03) variable nswalladiabatic is used before initialized
247 getheatflux_cd: (DF03) variable eulerwall is used before initialized
248 getheatflux_cd: (DF03) variable zero is used before initialized
249 getheatflux_cd: Tool: (Differentiate reference) Unexpected operator: call
250 getheatflux_cd: Tool: (TypeSpec tree regeneration) null actualTypeSpec
251 getheatflux_cd: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#22==0null*=>HB#21) label:100
252 getheatflux_cd: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#27==0null*=>HB#26) label:110
253 heatfluxes_cd: (DD15) Module constants is not defined
254 heatfluxes_cd: (DD15) Module blockpointers is not defined
255 heatfluxes_cd: (DD15) Module bcpointers is not defined
256 heatfluxes_cd: (DD15) Module flowvarrefstate is not defined
257 heatfluxes_cd: (DD15) Module utils is not defined
258 heatfluxes_cd: (TC20) Variable pref is not declared
259 heatfluxes_cd: (TC20) Variable rhoref is not declared
260 heatfluxes_cd: (TC20) Variable nbocos is not declared
261 heatfluxes_cd: (TC20) Variable nswallisothermal is not declared
262 heatfluxes_cd: (TC33) External procedure setbcpointers is not declared
263 heatfluxes_cd: (TC33) External procedure bcfaceid is not declared
264 heatfluxes_cd: (TC20) Variable imin is not declared
265 heatfluxes_cd: (TC20) Variable jmin is not declared
266 heatfluxes_cd: (TC20) Variable kmin is not declared
267 heatfluxes_cd: (TC20) Variable imax is not declared
268 heatfluxes_cd: (TC20) Variable jmax is not declared
269 heatfluxes_cd: (TC20) Variable kmax is not declared
270 heatfluxes_cd: (TC20) Variable one is not declared
271 heatfluxes_cd: (TC33) External procedure ssi is not declared
272 heatfluxes_cd: (TC33) External procedure viscsubface is not declared
273 heatfluxes_cd: (TC49) Unknown return type for function bctype 
274 heatfluxes_cd: (TC49) Unknown return type for function bcfaceid 
275 heatfluxes_cd: (TC44) Could not find type of result of function bctype, please check
276 heatfluxes_cd: (TC44) Could not find type of result of function bcfaceid, please check
277 heatfluxes_cd: (DF03) variable pref is used before initialized
278 heatfluxes_cd: (DF03) variable rhoref is used before initialized
279 heatfluxes_cd: (DF03) variable pref is used before initialized
280 heatfluxes_cd: (DF03) variable nbocos is used before initialized
281 heatfluxes_cd: (DF03) variable nswallisothermal is used before initialized
282 heatfluxes_cd: (DF03) variable one is used before initialized
283 heatfluxes_cd: (DF03) variable one is used before initialized
284 heatfluxes_cd: Tool: (TypeSpec tree regeneration) null actualTypeSpec
285 heatfluxes_cd: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#9==0null*=>HB#8) label:100
