1 getforces: (DD15) Module constants is not defined
2 getforces: (DD15) Module communication is not defined
3 getforces: (DD15) Module blockpointers is not defined
4 getforces: (DD15) Module inputphysics is not defined
5 getforces: (DD15) Module utils is not defined
6 getforces: (DD15) Module surfaceintegrations is not defined
7 getforces: (DD15) Module surfacefamilies is not defined
8 getforces: (DD15) Module oversetdata is not defined
9 getforces: (DD15) Module surfacefamilies is not defined
10 getforces: (DD15) Module petsc is not defined
11 getforces: (TC21) No implicit rule available to complete the declaration of variable nlocalvalues
12 getforces: (TC21) No implicit rule available to complete the declaration of variable ncostfunction
13 getforces: (TC62) Undeclared type: zippermesh
14 getforces: (TC62) Undeclared type: familyexchange
15 getforces: (TC20) Variable ndom is not declared
16 getforces: (TC33) External procedure setpointers is not declared
17 getforces: (TC20) Variable zero is not declared
18 getforces: (TC20) Variable fullfamlist is not declared
19 getforces: (TC33) External procedure integratesurfaces is not declared
20 getforces: (TC20) Variable forcesastractions is not declared
21 getforces: (TC33) External procedure computenodaltractions is not declared
22 getforces: (TC33) External procedure computenodalforces is not declared
23 getforces: (TC20) Variable nbocos is not declared
24 getforces: (TC33) External procedure bctype is not declared
25 getforces: (TC20) Variable eulerwall is not declared
26 getforces: (TC20) Variable nswalladiabatic is not declared
27 getforces: (TC20) Variable nswallisothermal is not declared
28 getforces: (TC33) External procedure bcdata is not declared
29 getforces: (TC20) Variable ibcgroupwalls is not declared
30 getforces: (TC33) External procedure zippermeshes is not declared
31 getforces: (TC33) External procedure bcfamexchange is not declared
32 getforces: (TC20) Variable oversetpresent is not declared
33 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
34 getforces: (TC33) External procedure terminate is not declared
35 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
36 getforces: (TC33) External procedure vecgetarrayf90 is not declared
37 getforces: (TC20) Variable __file__ is not declared
38 getforces: (TC20) Variable __line__ is not declared
39 getforces: (TC33) External procedure echk is not declared
40 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
41 getforces: (TC33) External procedure vecrestorearrayf90 is not declared
42 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
43 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
44 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
45 getforces: (TC20) Variable insert_values is not declared
46 getforces: (TC20) Variable scatter_forward is not declared
47 getforces: (TC33) External procedure vecscatterbegin is not declared
48 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
49 getforces: (TC03) Expression is expected to be a record, and is here familyexchange
50 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
51 getforces: (TC33) External procedure vecscatterend is not declared
52 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
53 getforces: (TC20) Variable myid is not declared
54 getforces: (TC03) Expression is expected to be a record, and is here zippermesh
55 getforces: (TC49) Unknown return type for function bctype 
56 getforces: (TC44) Could not find type of result of function bctype, please check
57 getforces: (TC44) Could not find type of result of function bctype, please check
58 getforces: (TC44) Could not find type of result of function bctype, please check
59 getforces: (DF03) variable nlocalvalues is used before initialized
60 getforces: (DF03) variable ndom is used before initialized
61 getforces: (DF03) variable zero is used before initialized
62 getforces: (DF03) variable forcesastractions is used before initialized
63 getforces: (DF03) variable ndom is used before initialized
64 getforces: (DF03) variable nbocos is used before initialized
65 getforces: (DF03) variable eulerwall is used before initialized
66 getforces: (DF03) variable nswalladiabatic is used before initialized
67 getforces: (DF03) variable nswallisothermal is used before initialized
68 getforces: (DF03) variable forcesastractions is used before initialized
69 getforces: (DF03) variable oversetpresent is used before initialized
70 getforces: (DF03) expression *zipper.allocated is undefined
71 getforces: (DF03) variable forcesastractions is used before initialized
72 getforces: (DF03) variable myid is used before initialized
73 getforces: (DF03) expression *localptr is undefined
74 getforces: Tool: (TypeSpec tree regeneration) null actualTypeSpec
75 getforces: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#15==0null*=>HB#13) label:100
76 getforces: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#16==0null*=>HB#13) label:100
77 getheatflux: (DD15) Module constants is not defined
78 getheatflux: (DD15) Module blockpointers is not defined
79 getheatflux: (DD15) Module surfacefamilies is not defined
80 getheatflux: (DD15) Module utils is not defined
81 getheatflux: (TC62) Undeclared type: familyexchange
82 getheatflux: (TC20) Variable ibcgroupwalls is not declared
83 getheatflux: (TC20) Variable ndom is not declared
84 getheatflux: (TC20) Variable nbocos is not declared
85 getheatflux: (TC20) Variable nswallisothermal is not declared
86 getheatflux: (TC60) bcdata(mm).cellval must be a pointer
87 getheatflux: (TC20) Variable eulerwall is not declared
88 getheatflux: (TC20) Variable nswalladiabatic is not declared
89 getheatflux: (TC20) Variable zerocellval is not declared
90 getheatflux: (TC60) bcdata(mm).cellval must be a pointer
91 getheatflux: (TC20) Variable zeronodeval is not declared
92 getheatflux: (TC60) bcdata(mm).nodeval must be a pointer
93 getheatflux: (TC33) External procedure computeweighting is not declared
94 getheatflux: (TC60) bcdata(mm).cellval must be a pointer
95 getheatflux: (TC60) bcdata(mm).nodeval must be a pointer
96 getheatflux: (TC33) External procedure surfacecellcentertonode is not declared
97 getheatflux: (TC20) Variable zero is not declared
98 getheatflux: (TC49) Unknown return type for function bctype 
99 getheatflux: (TC44) Could not find type of result of function bctype, please check
100 getheatflux: (TC44) Could not find type of result of function bctype, please check
101 getheatflux: (TC44) Could not find type of result of function bctype, please check
102 getheatflux: (TC44) Could not find type of result of function bctype, please check
103 getheatflux: (TC44) Could not find type of result of function bctype, please check
104 getheatflux: (TC44) Could not find type of result of function bctype, please check
105 getheatflux: (TC44) Could not find type of result of function bctype, please check
106 getheatflux: Tool: (TypeSpec tree regeneration) null actualTypeSpec
107 getheatflux: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#22==0null*=>HB#21) label:100
108 getheatflux: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#27==0null*=>HB#26) label:110
109 heatfluxes: (DD15) Module constants is not defined
110 heatfluxes: (DD15) Module blockpointers is not defined
111 heatfluxes: (DD15) Module bcpointers is not defined
112 heatfluxes: (DD15) Module flowvarrefstate is not defined
113 heatfluxes: (DD15) Module utils is not defined
114 heatfluxes: (TC20) Variable pref is not declared
115 heatfluxes: (TC20) Variable rhoref is not declared
116 heatfluxes: (TC20) Variable nbocos is not declared
117 heatfluxes: (TC20) Variable nswallisothermal is not declared
118 heatfluxes: (TC33) External procedure setbcpointers is not declared
119 heatfluxes: (TC33) External procedure bcfaceid is not declared
120 heatfluxes: (TC20) Variable imin is not declared
121 heatfluxes: (TC20) Variable jmin is not declared
122 heatfluxes: (TC20) Variable kmin is not declared
123 heatfluxes: (TC20) Variable imax is not declared
124 heatfluxes: (TC20) Variable jmax is not declared
125 heatfluxes: (TC20) Variable kmax is not declared
126 heatfluxes: (TC20) Variable one is not declared
127 heatfluxes: (TC33) External procedure ssi is not declared
128 heatfluxes: (TC33) External procedure viscsubface is not declared
129 heatfluxes: (TC49) Unknown return type for function bctype 
130 heatfluxes: (TC49) Unknown return type for function bcfaceid 
131 heatfluxes: (TC44) Could not find type of result of function bctype, please check
132 heatfluxes: (TC44) Could not find type of result of function bcfaceid, please check
133 heatfluxes: Tool: (TypeSpec tree regeneration) null actualTypeSpec
134 heatfluxes: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#9==0null*=>HB#8) label:100
135 getforces_d: Tool: (TypeSpec tree regeneration) null actualTypeSpec
136 getforces_d: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#15==0null==>HB#13) label:100
137 getforces_d: Tool: (Tree regeneration) Forgotten arrow carry of FGA(BB#16==0null==>HB#13) label:100
